export const THEME = {
  name: "classic-light",
  motionIntensity: "low",
  colors: {
    bgStart: "#F8FAFC",
    bgEnd: "#EEF2F6",
    surface: "#FFFFFF",
    surfaceMuted: "#F3F4F6",
    border: "#E5E7EB",
    borderStrong: "#CBD5E1",
    accent: "#2563EB",
    accentSoft: "#DBEAFE",
    accentStrong: "#1D4ED8",
    danger: "#B91C1C",
    dangerSoft: "#FEE2E2",
    success: "#047857",
    successSoft: "#D1FAE5",
    warning: "#B45309",
    warningSoft: "#FEF3C7",
    textPrimary: "#0F172A",
    textSecondary: "#475569",
    textMuted: "#94A3B8",
  },
} as const;
